<img src="Images/PU.png" width="100%">

## Course Name : Python for Data Analysis 
#### Notebook compiled by : Bhushan Garware, Project Lead at Learning and Development  
** Important ! ** For internal circulation olny

#  Assignment No. 1 

This assignment is designed to test your ** Pandas Fundamentals. **  We would be working on the *' [Medical No-Shows](https://www.kaggle.com/joniarroba/noshowappointments)'* dataset availabe on Kaggle. Dataset is already downloaded and you can get it easily form here.

### Required imports

In [21]:
import numpy as np

In [22]:
import pandas as pd

### Read dataset form local file

In [23]:
df=pd.read_csv("./Datasets/No-show-Issue-Comma-300k.csv")
df.dropna()

,Age,Gender,AppointmentRegistration,ApointmentData,DayOfTheWeek,Status,Diabetes,Alcoolism,HiperTension,Handcap,Smokes,Scholarship,Tuberculosis,Sms_Reminder,AwaitingTime
0,19,M,2014-12-16T14:46:25Z,2015-01-14T00:00:00Z,Wednesday,Show-Up,0,0,0,0,0,0,0,0,-29
1,24,F,2015-08-18T07:01:26Z,2015-08-19T00:00:00Z,Wednesday,Show-Up,0,0,0,0,0,0,0,0,-1
2,4,F,2014-02-17T12:53:46Z,2014-02-18T00:00:00Z,Tuesday,Show-Up,0,0,0,0,0,0,0,0,-1
3,5,M,2014-07-23T17:02:11Z,2014-08-07T00:00:00Z,Thursday,Show-Up,0,0,0,0,0,0,0,1,-15
4,38,M,2015-10-21T15:20:09Z,2015-10-27T00:00:00Z,Tuesday,Show-Up,0,0,0,0,0,0,0,1,-6
5,5,F,2014-06-17T06:47:27Z,2014-07-22T00:00:00Z,Tuesday,No-Show,0,0,0,0,0,0,0,1,-35
6,46,F,2015-06-19T19:53:58Z,2015-07-07T00:00:00Z,Tuesday,Show-Up,0,0,0,0,0,0,0,1,-18
7,4,F,2015-08-07T08:19:19Z,2015-08-21T00:00:00Z,Friday,Show-Up,0,0,0,0,0,1,0,1,-14
8,20,F,2014-10-14T11:46:36Z,2014-10-28T00:00:00Z,Tuesday,Show-Up,0,0,0,0,0,0,0,0,-14
9,51,F,2014-06-13T07:50:43Z,2014-06-17T00:00:00Z,Tuesday,Show-Up,1,0,1,0,0,0,0,1,-4
10,33,M,2015-10-01T08:43:18Z,2015-11-09T00:00:00Z,Monday,Show-Up,0,0,0,0,0,0,0,0,-39
11,58,F,2014-04-30T08:04:27Z,2014-05-22T00:00:00Z,Thursday,Show-Up,0,0,1,0,0,1,0,1,-22
12,62,F,2014-07-25T15:02:33Z,2014-08-11T00:00:00Z,Monday,No-Show,1,0,1,0,0,0,0,0,-17
13,62,F,2014-07-08T12:56:25Z,2014-07-14T00:00:00Z,Monday,Show-Up,0,0,0,0,0,0,0,1,-6
14,38,M,2014-03-21T08:23:16Z,2014-03-27T00:00:00Z,Thursday,No-Show,0,0,0,0,0,0,0,1,-6
15,73,M,2015-04-01T16:27:05Z,2015-04-02T00:00:00Z,Thursday,Show-Up,0,0,1,0,0,0,0,0,-1
16,48,F,2015-03-07T10:45:25Z,2015-03-30T00:00:00Z,Monday,Show-Up,0,0,0,0,0,0,0,1,-23
17,52,M,2014-06-03T10:20:37Z,2014-06-05T00:00:00Z,Thursday,No-Show,0,0,0,0,0,0,0,0,-2
18,64,F,2014-02-17T14:32:34Z,2014-02-24T00:00:00Z,Monday,Show-Up,1,0,1,0,0,0,0,1,-7
19,1,M,2014-04-01T13:39:00Z,2014-04-02T00:00:00Z,Wednesday,Show-Up,0,0,0,0,0,0,0,0,-1
20,33,F,2014-03-12T10:26:26Z,2014-03-15T00:00:00Z,Saturday,Show-Up,0,0,0,0,0,0,0,0,-3
21,44,F,2015-04-08T12:31:28Z,2015-04-10T00:00:00Z,Friday,Show-Up,0,0,0,0,0,0,0,0,-2
22,5,F,2015-11-11T09:44:38Z,2015-11-12T00:00:00Z,Thursday,Show-Up,0,0,0,0,0,0,0,0,-1
23,69,F,2014-11-24T08:25:35Z,2014-11-28T00:00:00Z,Friday,Show-Up,1,0,1,0,0,0,0,0,-4
24,16,F,2014-10-23T16:49:42Z,2014-10-28T00:00:00Z,Tuesday,No-Show,0,0,0,1,0,0,0,0,-5
25,8,M,2015-05-11T14:56:01Z,2015-05-25T00:00:00Z,Monday,No-Show,0,0,0,0,0,0,0,1,-14
26,7,M,2015-04-01T08:45:19Z,2015-04-16T00:00:00Z,Thursday,Show-Up,0,0,0,0,0,0,0,0,-15
27,51,F,2014-07-29T10:33:20Z,2014-07-31T00:00:00Z,Thursday,Show-Up,0,0,0,0,0,0,0,0,-2
28,29,F,2014-08-18T10:30:16Z,2014-08-20T00:00:00Z,Wednesday,Show-Up,0,0,0,0,0,0,0,0,-2
29,59,M,2014-02-12T08:29:48Z,2014-03-14T00:00:00Z,Friday,No-Show,0,0,0,0,0,0,0,1,-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299970,74,F,2015-09-02T17:17:18Z,2015-09-09T00:00:00Z,Wednesday,Show-Up,0,0,1,0,0,0,0,1,-7
299971,9,M,2014-07-01T07:21:56Z,2014-07-03T00:00:00Z,Thursday,No-Show,0,0,0,0,0,0,0,0,-2
299972,28,M,2015-07-14T09:07:11Z,2015-07-20T00:00:00Z,Monday,Show-Up,0,0,0,0,1,0,0,1,-6
299973,47,M,2014-09-03T18:43:46Z,2014-09-11T00:00:00Z,Thursday,Show-Up,0,0,0,0,0,0,0,1,-8
299974,61,M,2015-04-09T12:55:52Z,2015-04-10T00:00:00Z,Friday,Show-Up,0,0,1,0,0,0,0,0,-1
299975,13,M,2015-12-22T08:13:21Z,2015-12-23T00:00:00Z,Wednesday,Show-Up,0,0,0,0,0,0,0,0,-1
299976,52,F,2014-05-19T12:16:19Z,2014-05-21T00:00:00Z,Wednesday,No-Show,0,0,1,0,0,1,0,0,-2
299977,46,F,2014-10-01T08:16:09Z,2014-10-10T00:00:00Z,Friday,Show-Up,0,0,0,0,0,0,0,1,-9
299978,70,F,2014-06-30T09:29:04Z,2014-07-01T00:00:00Z,Tuesday,Show-Up,0,0,0,0,0,0,0,0,-1
299979,42,M,2014-03-24T11:10:44Z,2014-03-26T00:00:00Z,Wednesday,Show-Up,0,0,0,0,0,0,0,0,-2
299980,7,F,2015-10-01T16:58:44Z,2015-10-13T00:00:00Z,Tuesday,No-Show,0,0,0,0,0,0,0,1,-12
299981,56,M,2014-11-21T17:15:48Z,2014-11-25T00:00:00Z,Tuesday,Show-Up,0,0,0,0,0,0,0,0,-4
299982,84,F,2014-11-04T13:54:47Z,2014-11-07T00:00:00Z,Friday,No-Show,0,0,1,0,0,0,0,0,-3
299983,4,F,2015-04-29T13:46:40Z,2015-04-30T00:00:00Z,Thursday,Show-Up,0,0,0,0,0,0,0,0,-1
299984,5,F,2015-04-28T07:28:21Z,2015-05-27T00:00:00Z,Wednesday,Show-Up,0,0,0,0,0,0,0,1,-29
299985,0,F,2015-06-16T16:01:27Z,2015-07-14T00:00:00Z,Tuesday,No-Show,0,0,0,0,0,0,0,0,-28
299986,67,F,2014-04-08T11:00:28Z,2014-04-10T00:00:00Z,Thursday,Show-Up,1,0,1,0,0,0,0,0,-2
299987,73,F,2015-09-24T18:47:15Z,2015-10-28T00:00:00Z,Wednesday,Show-Up,0,0,0,0,0,0,0,0,-34
299988,10,M,2014-01-15T09:28:31Z,2014-01-21T00:00:00Z,Tuesday,Show-Up,0,0,0,0,0,0,0,1,-6
299989,56,M,2014-12-17T16:23:46Z,2014-12-18T00:00:00Z,Thursday,Show-Up,0,0,0,0,0,0,0,0,-1
299990,55,M,2015-06-12T07:22:07Z,2015-06-19T00:00:00Z,Friday,No-Show,1,1,1,0,1,0,0,1,-7
299991,46,M,2015-07-15T15:24:36Z,2015-07-21T00:00:00Z,Tuesday,Show-Up,0,1,1,0,0,0,0,1,-6
299992,27,F,2014-09-09T07:46:33Z,2014-09-15T00:00:00Z,Monday,Show-Up,0,0,0,0,0,0,0,1,-6
299993,49,F,2015-01-15T08:44:24Z,2015-02-10T00:00:00Z,Tuesday,No-Show,0,0,0,0,1,0,0,1,-26
299994,17,M,2014-07-09T14:50:21Z,2014-07-11T00:00:00Z,Friday,Show-Up,0,0,0,0,0,0,0,0,-2
299995,41,M,2014-03-24T09:28:22Z,2014-04-16T00:00:00Z,Wednesday,Show-Up,0,0,1,0,0,0,0,1,-23
299996,67,F,2014-11-21T12:00:36Z,2014-11-25T00:00:00Z,Tuesday,Show-Up,1,0,1,0,0,0,0,1,-4
299997,48,F,2014-07-24T15:46:38Z,2014-07-25T00:00:00Z,Friday,No-Show,0,0,0,0,0,1,0,0,-1
299998,5,M,2015-05-15T09:58:50Z,2015-05-21T00:00:00Z,Thursday,Show-Up,0,0,0,0,0,0,0,0,-6
299999,0,M,2015-06-12T14:34:25Z,2015-07-15T00:00:00Z,Wednesday,Show-Up,0,0,0,0,0,0,0,1,-33

### Print first five rows of the dataset

In [24]:
df.head()

,Age,Gender,AppointmentRegistration,ApointmentData,DayOfTheWeek,Status,Diabetes,Alcoolism,HiperTension,Handcap,Smokes,Scholarship,Tuberculosis,Sms_Reminder,AwaitingTime
0,19,M,2014-12-16T14:46:25Z,2015-01-14T00:00:00Z,Wednesday,Show-Up,0,0,0,0,0,0,0,0,-29
1,24,F,2015-08-18T07:01:26Z,2015-08-19T00:00:00Z,Wednesday,Show-Up,0,0,0,0,0,0,0,0,-1
2,4,F,2014-02-17T12:53:46Z,2014-02-18T00:00:00Z,Tuesday,Show-Up,0,0,0,0,0,0,0,0,-1
3,5,M,2014-07-23T17:02:11Z,2014-08-07T00:00:00Z,Thursday,Show-Up,0,0,0,0,0,0,0,1,-15
4,38,M,2015-10-21T15:20:09Z,2015-10-27T00:00:00Z,Tuesday,Show-Up,0,0,0,0,0,0,0,1,-6

In [25]:
gender_mapping = {'M': 1,'F': 0}
df["Gender"] = df["Gender"].map(gender_mapping)

In [26]:
Status_mapping = {'Show-Up': 1,'No-Show': 0}
df["Status"] = df["Status"].map(Status_mapping)

In [27]:
X=df[['Age','Gender','Diabetes','Alcoolism','HiperTension']].values

In [28]:
#X=df[['Age','Gender','Diabetes','Alcoolism','HiperTension','Handcap','Smokes','Scholarship','Tuberculosis','Sms_Reminder','AwaitingTime']].values

In [29]:
y=df[['Status']].values

In [30]:
from sklearn.tree import DecisionTreeClassifier

In [31]:
# fit a CART model to the data
model = DecisionTreeClassifier()
model.fit(X, y)
print(model)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [32]:
expected = y
predicted = model.predict(X)

In [33]:
from sklearn import metrics
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

             precision    recall  f1-score   support

          0       0.58      0.01      0.02     90731
          1       0.70      1.00      0.82    209269

avg / total       0.66      0.70      0.58    300000

[[   843  89888]
 [   616 208653]]

In [34]:
model.score(X,y)

0.69832000000000005

# Logistic Regression

In [35]:
from sklearn.linear_model import LogisticRegression

In [36]:
model = LogisticRegression(C=100)
model.fit(X, y)

LogisticRegression(C=100, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [37]:
model.score(X,y)

0.69756333333333331

# Navive Bayes

In [38]:
from sklearn.naive_bayes import GaussianNB

In [39]:
model = GaussianNB()
model.fit(X, y)

GaussianNB(priors=None)

In [40]:
model.score(X,y)

0.69133333333333336

# KNN Algorithm